apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: agent-sc
  labels:
   io.kompose.service: agent-claim
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: agent-pv
  labels:
    io.kompose.service: agent-claim
spec:
  storageClassName: agent-sc
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/hdfs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: agent-claim
  name: agent-claim0
spec:
  storageClassName: agent-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
