apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: agent
  name: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: agent
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: agent
    spec:
      containers:
        - env:
            - name: MONGODB_ADDRESS
              value: mongodb://mongo.:27017/
            - name: REPORTS_FOLDER
              value: /tmp/mlreports
            - name: REPORT_TIME_WINDOW_MINUTES
              value: "180"
          image: prefect_agent_1
          name: prefect-agent-1
          resources: {}
          volumeMounts:
            - mountPath: /tmp/mlopsdb
              name: agent-claim0
            - mountPath: /tmp/mlopsartifacts
              name: agent-claim1
            - mountPath: /tmp/store
              name: agent-claim2
            - mountPath: /tmp/mlreports
              name: agent-claim3
      restartPolicy: Always
      volumes:
        - name: agent-claim0
          persistentVolumeClaim:
            claimName: agent-claim0
        - name: agent-claim1
          persistentVolumeClaim:
            claimName: agent-claim1
        - name: agent-claim2
          persistentVolumeClaim:
            claimName: agent-claim2
        - name: agent-claim3
          persistentVolumeClaim:
            claimName: agent-claim3
status: {}
