apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: agent-sc1
  labels:
   io.kompose.service: agent-claim1
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: agent-pv1
  labels:
    io.kompose.service: agent-claim1
spec:
  storageClassName: agent-sc1
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/hdfs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: agent-claim1
  name: agent-claim1
spec:
  storageClassName: agent-sc1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
