apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mlflow-sc2
  labels:
   io.kompose.service: mlflow-server
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-pv2
  labels:
    io.kompose.service: mlflow-server
spec:
  storageClassName: mlflow-sc2
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/hdfs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mlflow-server
  name: mlflow-server-claim2
spec:
  storageClassName: mlflow-sc2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
