apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mlflow-server
  name: mlflow-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mlflow-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: mlflow-server
    spec:
      containers:
        - image: neha2299/mlflow-server
          name: mlflow-server
          ports:
            - containerPort: 5050
          resources: {}
          volumeMounts:
            - mountPath: /tmp/mlopsdb
              name: mlflow-server-claim0
            - mountPath: /tmp/mlopsartifacts
              name: mlflow-server-claim1
            - mountPath: /tmp/store
              name: mlflow-server-claim2
      restartPolicy: Always
      volumes:
        - name: mlflow-server-claim0
          persistentVolumeClaim:
            claimName: mlflow-server-claim0
        - name: mlflow-server-claim1
          persistentVolumeClaim:
            claimName: mlflow-server-claim1
        - name: mlflow-server-claim2
          persistentVolumeClaim:
            claimName: mlflow-server-claim2
status: {}
