apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: serve-kinesis
  name: serve-kinesis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: serve-kinesis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.network/external: "true"
        io.kompose.service: serve-kinesis
    spec:
      containers:
        - env:
            - name: KINESIS_ADDRESS
              value: http://aws:4566
            - name: MLFLOW_ADDRESS
              value: http://mlflow_server:5050
            - name: RESULTS_STREAM_NAME
              value: results
          image: serve-kinesis
          name: serve-kinesis
          resources: {}
          volumeMounts:
            - mountPath: /tmp/mlopsdb
              name: serve-kinesis-claim0
            - mountPath: /tmp/mlopsartifacts
              name: serve-kinesis-claim1
            - mountPath: /tmp/store
              name: serve-kinesis-claim2
            - mountPath: /tmp/serve
              name: serve-kinesis-claim3
      restartPolicy: Always
      volumes:
        - name: serve-kinesis-claim0
          persistentVolumeClaim:
            claimName: serve-kinesis-claim0
        - name: serve-kinesis-claim1
          persistentVolumeClaim:
            claimName: serve-kinesis-claim1
        - name: serve-kinesis-claim2
          persistentVolumeClaim:
            claimName: serve-kinesis-claim2
        - name: serve-kinesis-claim3
          persistentVolumeClaim:
            claimName: serve-kinesis-claim3
status: {}
